// Builds the .xlsx file for an audit from rows that the audit rules already prepared. The workbook gets exactly the columns it is
// handed, so a PBM file (whose rows never held money) cannot contain a price: this file checks again before it writes anything.

import ExcelJS from "exceljs";
import { MONEY_KEYS, TEMPLATE_VERSION, TYPE_LABEL, assertPbmSafe, usDate, type AuditType, type ColumnDef, type ReportRow } from "@/lib/audit-rules";

export type WorkbookInfo = {
  type: AuditType;
  caseNumber: string;
  /** Shown on the AUDIT INFORMATION sheet; leave null to leave the line out (for example a regulatory file that names no pharmacy). */
  pharmacyName: string | null;
  ncpdp: string | null;
  start: string;
  end: string;
  auditor: string | null;
  requestingOrganization: string | null;
  /** Regulatory files: the kind of regulator and the reference number the regulator gave. */
  subtype?: string | null;
  reference?: string | null;
  generatedOn: string;
  generatedBy: string | null;
};

const HEADER_FILL: ExcelJS.Fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE8E4DA" } };
const MONEY_FMT = '"$"#,##0.00';

/** "YYYY-MM-DD" -> a real Excel date (midnight UTC, so no time zone can move the day). */
const toDate = (d: string) => new Date(`${d}T00:00:00.000Z`);

export async function buildAuditWorkbook(info: WorkbookInfo, columns: ColumnDef[], rows: ReportRow[]): Promise<Buffer> {
  if (info.type === "PBM") {
    assertPbmSafe(columns);
    for (const r of rows) for (const k of MONEY_KEYS) if (k in r) throw new Error("A PBM audit file can never contain pricing or shipping.");
  }
  const wb = new ExcelJS.Workbook();
  wb.creator = "Ledger Audit Center";
  wb.created = new Date(`${info.generatedOn}T12:00:00.000Z`);

  // Sheet 1: who and what this file is about. Only text and dates; nothing financial, ever.
  const meta = wb.addWorksheet("AUDIT INFORMATION");
  const lines: [string, string][] = [
    ["Audit Case Number", info.caseNumber],
    ["Audit Type", TYPE_LABEL[info.type]],
  ];
  if (info.pharmacyName) lines.push(["Pharmacy", info.pharmacyName]);
  if (info.ncpdp && (info.type === "PBM" || info.pharmacyName)) lines.push(["NCPDP", info.ncpdp]);
  lines.push(["Requested Period", `${usDate(info.start)} to ${usDate(info.end)}`]);
  if (info.auditor) lines.push(["Auditor", info.auditor]);
  if (info.requestingOrganization) lines.push(["Requesting Organization", info.requestingOrganization]);
  if (info.subtype) lines.push(["Regulator Type", info.subtype]);
  if (info.reference) lines.push(["Request Reference", info.reference]);
  lines.push(["Generated", usDate(info.generatedOn)]);
  if (info.generatedBy) lines.push(["Generated By", info.generatedBy]);
  lines.push(["Template", TEMPLATE_VERSION[info.type]]);
  for (const [k, v] of lines) {
    const r = meta.addRow([k, v]);
    r.getCell(1).font = { bold: true };
  }
  meta.getColumn(1).width = 26;
  meta.getColumn(2).width = Math.min(70, Math.max(24, ...lines.map(([, v]) => v.length + 2)));

  // Sheet 2: one transaction line per row.
  const ws = wb.addWorksheet("PURCHASE RECORDS");
  ws.columns = columns.map((c) => ({ header: c.header, key: c.key }));
  const widths = columns.map((c) => c.header.length + 2);
  for (const row of rows) {
    const values: Record<string, string | number | Date | null> = {};
    columns.forEach((c, i) => {
      const v = row[c.key] ?? null;
      let cell: string | number | Date | null = v;
      if (v !== null && c.kind === "date" && typeof v === "string") cell = toDate(v);
      values[c.key] = cell;
      const shown = v === null ? 0 : c.kind === "date" ? 10 : c.kind === "money" ? 12 : String(v).length;
      widths[i] = Math.max(widths[i], Math.min(60, shown + 2));
    });
    ws.addRow(values);
  }
  columns.forEach((c, i) => {
    const col = ws.getColumn(i + 1);
    col.width = widths[i];
    if (c.kind === "date") col.numFmt = "mm/dd/yyyy";
    else if (c.kind === "money") col.numFmt = MONEY_FMT;
    else if (c.kind === "int") col.numFmt = "0";
    else col.numFmt = "@"; // NDC/NRC and invoice numbers stay exactly as typed
  });
  const head = ws.getRow(1);
  head.font = { bold: true };
  head.alignment = { vertical: "middle", wrapText: true };
  head.eachCell((cell) => {
    cell.fill = HEADER_FILL;
  });
  ws.views = [{ state: "frozen", ySplit: 1 }];
  if (columns.length) ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };

  return Buffer.from(await wb.xlsx.writeBuffer());
}

/** Reads a workbook back into plain text per sheet. Used by the tests and by the "no prices in a PBM file" check. */
export async function readWorkbookText(buf: Buffer | Uint8Array): Promise<{ sheets: { name: string; rows: (string | number | null)[][] }[]; hiddenSheets: number }> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(buf as unknown as ArrayBuffer);
  let hidden = 0;
  const sheets = wb.worksheets.map((ws) => {
    if (ws.state !== "visible") hidden += 1;
    const rows: (string | number | null)[][] = [];
    ws.eachRow({ includeEmpty: false }, (r) => {
      const vals: (string | number | null)[] = [];
      r.eachCell({ includeEmpty: true }, (c) => {
        const v = c.value;
        vals.push(v === null || v === undefined ? null : v instanceof Date ? v.toISOString().slice(0, 10) : typeof v === "object" ? JSON.stringify(v) : (v as string | number));
      });
      rows.push(vals);
    });
    return { name: ws.name, rows };
  });
  return { sheets, hiddenSheets: hidden };
}
